"""Regenerate scripts/INDEX.md from module docstrings, imports and repository citations."""
import ast, re, subprocess, zipfile
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
# First matching token wins; order matters.
STREAMS = [
    ('chicago_m3', 'Chicago M3/M4 physical blocks (active frontier)'),
    (('block', 'rail', 'pedestrian'), 'SP–Chicago block-boundary pilots (M3/M4)'),
    ('u1', 'U1 land-use pilots'),
    ('m1', 'M1/M6 street-network review'),
    ('employment', 'Chicago U2 employment sensitivity'),
    (('harmoniz', 'microsoft', 'ghsl', 'matched', 'sp_bus'), 'SP–Chicago harmonization (H0–H4)'),
    (('chicago', 'cook'), 'Chicago local attributes and sources'),
    (('sp', 'sao_paulo', 'rais'), 'São Paulo pipeline (frozen release)'),
]


def stream(name):
    low = name.lower()
    for keys, label in STREAMS:
        if any(k in low for k in ([keys] if isinstance(keys, str) else keys)):
            return label
    return 'Other'


def purpose(path):
    doc = ast.get_docstring(ast.parse(path.read_text())) or '(no docstring)'
    line = ' '.join(doc.split('\n\n')[0].split())
    return (line[:180] + '…' if len(line) > 180 else line).replace('|', '\\|')


def citations(name):
    out = subprocess.run(['git', 'grep', '-l', f'{name}.py', '--', ':!analysis/scripts'],
                         cwd=ROOT, capture_output=True, text=True).stdout.split()
    return sorted({'/'.join(p.split('/')[:4]) for p in out})


scripts = sorted(HERE.glob('*.py'))
names = {p.stem for p in scripts}
importers = defaultdict(set)
for p in [*scripts, *HERE.glob('*/*.py'), *(ROOT / 'analysis/tests').glob('*.py')]:
    for mod in re.findall(r'^\s*(?:from|import)\s+(\w+)', p.read_text(), re.M):
        if mod in names and mod != p.stem:
            importers[mod].add(p.stem)

groups = defaultdict(list)
for p in scripts:
    if p.stem != 'make_index':
        groups[stream(p.stem)].append(p)

lines = ['# Script index', '',
         'Generated by `make_index.py`; rerun after adding, archiving or documenting a script. '
         '**Purpose** is the module docstring; **imported by** lists scripts/tests that import it '
         '(do not archive those alone); **cited in** lists doc/result folders naming it.', '',
         'Scripts stay flat: they resolve the repo root with `parents[2]` and import each other as '
         'top-level modules. Run them from the repository root with `.venv/bin/python analysis/scripts/<name>.py`.', '']
for label in [label for _, label in STREAMS] + ['Other']:
    if label not in groups:
        continue
    lines += [f'## {label}', '', '| Script | Purpose | Imported by | Cited in |', '|---|---|---|---|']
    for p in groups[label]:
        cited = citations(p.stem)
        lines.append(f'| `{p.name}` | {purpose(p)} | {", ".join(sorted(importers[p.stem])) or "—"} | '
                     f'{"<br>".join(cited[:3]) + (f" (+{len(cited) - 3})" if len(cited) > 3 else "") or "—"} |')
    lines.append('')

lines += ['## Library packages', '',
          '| Package | Role |', '|---|---|',
          '| `harmonization/` | Shared SP–Chicago geometry, roads, junctions, rasters, functional and employment helpers |',
          '| `sp_attributes/` | SP attribute construction (core, spatial, tabular) |',
          '| `sp_model/` | SP similarity model: inputs, transforms, distances, sensitivity, reporting, review |',
          '| `sp_v3/` | SP v3 preparation stages (geography, fiscal, network, demography, transit, acceptance) |', '',
          '## Config bindings (`analysis/config/`)', '',
          'Frozen method contracts; a change is a new versioned file, never an edit. '
          '"Read by" lists live code naming the file; archived scripts are not searched.', '',
          '| Config | Read by |', '|---|---|']
code = {p: p.read_text() for p in [*HERE.glob('*.py'), *HERE.glob('*/*.py'),
                                   *(ROOT / 'analysis/tests').glob('*.py'), *(ROOT / 'analysis/curio_nodes').glob('*.py')]}
configs = sorted((ROOT / 'analysis/config').iterdir())
for c in configs:
    users = sorted(p.stem for p, text in code.items() if c.name in text and p.stem != 'make_index')
    users += [o.name for o in configs if o != c and o.suffix == '.json' and c.name in o.read_text()]
    lines.append(f'| `{c.name}` | {", ".join(users) or "— (cited by docs only)"} |')
lines += ['', '## Archived (`_archive/*.zip`)', '',
          'Finished leaf scripts; nothing live imports them. To run one, unzip it into this folder '
          '(`unzip _archive/<zip> <script>.py`). Originals are also at git tag `pre-restructure`.', '',
          '| Archive | Scripts |', '|---|---|']
for z in sorted((HERE / '_archive').glob('*.zip')):
    lines.append(f'| `{z.name}` | {", ".join(f"`{n}`" for n in sorted(zipfile.ZipFile(z).namelist()))} |')
(HERE / 'INDEX.md').write_text('\n'.join(lines) + '\n')
print(f'indexed {sum(1 for p in scripts) - 1} scripts')
